
-- O U IDENTIFICA TABELA
IF OBJECT_ID('TABELA_TESTE', 'U') IS NOT NULL DROP TABLE TABELA_TESTE

IF OBJECT_ID('TABELA_TESTE', 'U') IS NULL  CREATE TABLE TABELA_TESTE (ID VARCHAR (10))

SELECT GETDATE()
SELECT DATENAME(WEEKDAY, DATEADD(DAY,7, GETDATE()))

DECLARE @DIA_SEMANA VARCHAR(20)
DECLARE @NUMERO_DIAS INT

SET @NUMERO_DIAS = 7
SET @DIA_SEMANA =  DATENAME(WEEKDAY, DATEADD(DAY, @NUMERO_DIAS , GETDATE()))
PRINT @DIA_SEMANA
IF @DIA_SEMANA = 'Sunday' or @DIA_SEMANA = 'Saturday'
	PRINT 'Este dia é fim de semana'
ELSE
	PRINT 'Este dia é dia da semana'


/*Crie um script que, baseado em uma data, conte o número de notas fiscais. Se houver mais de 70 notas, exiba a mensagem
"Muita nota". Se não, exiba a mensagem "Pouca nota". Exiba também o número de notas.
=*/

DECLARE @QTDNOTA  INT
DECLARE @DIA DATE

SET @DIA = '20150101'

SELECT @QTDNOTA = COUNT(*) FROM [NOTAS FISCAIS] 
WHERE
DATA = @DIA
IF @QTDNOTA > 70
	PRINT 'Muita nota'
ELSE 
	PRINT 'Pouca nota'
PRINT @QTDNOTA


SELECT SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = 'Jardins'

DECLARE @LIMITE_MAXIMO FLOAT, @LIMITE_ATUAL FLOAT
DECLARE @BAIRRO VARCHAR(20)

SET @BAIRRO = 'Jardins'
SET @LIMITE_MAXIMO = 400000

SELECT @LIMITE_ATUAL = SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = @BAIRRO
IF @LIMITE_MAXIMO <= (SELECT SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = @BAIRRO)
BEGIN 
	PRINT 'Valor estourou. Não é possível abrir novos créditos'
END
ELSE
BEGIN 
	PRINT 'Valor não estourou. É possível abrir novos créditos'
END

/*Baseado no script de resposta do exercício anterior:*/


DECLARE @DATANOTA DATE
DECLARE @NUMNOTAS INT
SET @DATANOTA = '20170102'
SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
    WHERE DATA = @DATANOTA
IF @NUMNOTAS > 70
    PRINT 'Muita nota'
ELSE
    PRINT 'Pouca nota'
PRINT @NUMNOTAS



DECLARE @DATANOTA2 DATE
SET @DATANOTA2 = '20170102'
IF (SELECT COUNT(*) FROM [NOTAS FISCAIS] 
        WHERE DATA = @DATANOTA2) > 70
    PRINT 'Muita nota'
ELSE
    PRINT 'Pouca nota'
