-- Retorna o valor total de uma nota fiscal 
SELECT SUM(QUANTIDADE * [PREÇO]) FROM [ITENS NOTAS FISCAIS]
WHERE NUMERO = 100


-- Função da query acima
CREATE FUNCTION FaturamentoNota(@NUMERO AS INT) RETURNS FLOAT
AS
BEGIN
	DECLARE @FATURAMENTO FLOAT
	SELECT @FATURAMENTO = SUM(QUANTIDADE * [PREÇO]) FROM [ITENS NOTAS FISCAIS]
	WHERE NUMERO = @NUMERO
	RETURN @FATURAMENTO
END


SELECT NUMERO, [dbo].[FaturamentoNota](NUMERO) AS FATURAMENTO FROM [NOTAS FISCAIS]


/*Transforme este script em uma função onde passamos a data como parâmetro e retornamos o número de notas. 
Chame esta função de NumeroNotas. Após a sua criação, teste seu uso com um SELECT.*/


DECLARE @NUMNOTAS INT
SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
    WHERE DATA = '20170101'
PRINT @NUMNOTAS

CREATE FUNCTION NUMERONOTAS (@DATA DATE) RETURNS INT
AS
BEGIN
DECLARE @NUMNOTAS INT
SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS] 
    WHERE DATA = @DATA
RETURN @NUMNOTAS
END

SELECT [dbo].[NUMERONOTAS]('20170202')