DECLARE @MATRICULA VARCHAR(5), @NOME VARCHAR(100), @PERCENTUAL FLOAT, @DATA DATE, @FERIAS BIT
DECLARE @BAIRRO VARCHAR(100)

SET @MATRICULA = '00239'
SET @NOME = 'José Mattos'
SET @PERCENTUAL = 0.10
SET @DATA = '20100120'
SET @FERIAS = 1
SET @BAIRRO = 'Pimentas'

INSERT INTO [TABELA DE VENDEDORES] (MATRICULA, NOME, [PERCENTUAL COMISSÃO],[DATA ADMISSÃO],[DE FERIAS],BAIRRO)
VALUES
(@MATRICULA,@NOME,@PERCENTUAL,@DATA,@FERIAS,@BAIRRO)



SELECT * FROM [TABELA DE VENDEDORES]