SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Manga'


/* Digamos que queiramos classificar os nossos produtos de, Baratos, caros e produtos  em conta */
SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
(CASE WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
	  WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
	  ELSE 'PRODUTO BARATO' END) AS CLASSIFICACAO
FROM TABELA_DE_PRODUTOS
WHERE SABOR = 'Manga'          
ORDER BY CLASSIFICACAO;

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
(CASE WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
	  WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
	  ELSE 'PRODUTO BARATO' END) AS CLASSIFICACAO
FROM TABELA_DE_PRODUTOS        
ORDER BY CLASSIFICACAO;

SELECT
(CASE WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
	  WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
	  ELSE 'PRODUTO BARATO' END) AS CLASSIFICACAO, COUNT(*) AS NUMERO_DE_PRODUTOS
FROM TABELA_DE_PRODUTOS
GROUP BY (CASE WHEN PRECO_DE_LISTA >= 12 THEN 'PRODUTO CARO'
	  WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
	  ELSE 'PRODUTO BARATO' END);



/*Para cada cliente temos seus limites de crédito mensais. Liste somente o nome dos clientes e os classifique por:

Acima ou igual a 150.000 - Clientes grandes
Entre 150.000 e 110.000 - Clientes médios
Menores que 110.000 Clientes pequenos*/

SELECT NOME,
	   LIMITE_DE_CREDITO,
(CASE WHEN LIMITE_DE_CREDITO >= 150000 THEN 'Clientes grandes'
	  WHEN LIMITE_DE_CREDITO >= 110000 AND LIMITE_DE_CREDITO >= 150000 THEN 'Clientes médios'
	  ELSE 'Clientes pequenos' 
END) AS CLASSIFICACAO_CLIENTES
FROM
	TABELA_DE_CLIENTES
ORDER BY
	LIMITE_DE_CREDITO DESC;

SELECT NOME,
	   LIMITE_DE_CREDITO,
(CASE WHEN LIMITE_DE_CREDITO >= 150000 THEN 'Clientes grandes'
	  WHEN LIMITE_DE_CREDITO >= 110000 AND LIMITE_DE_CREDITO >= 150000 THEN 'Clientes médios'
	  ELSE 'Clientes pequenos' 
END) AS CLASSIFICACAO_CLIENTES
FROM
	TABELA_DE_CLIENTES
ORDER BY
	LIMITE_DE_CREDITO DESC;


SELECT NOME,
(CASE WHEN LIMITE_DE_CREDITO >= 150000 THEN 'Clientes grandes'
WHEN LIMITE_DE_CREDITO < 150000 AND LIMITE_DE_CREDITO >= 110000 THEN 'Clientes medios'
ELSE 'Clientes pequenos' END) AS CLASSIFICACAO
FROM TABELA_DE_CLIENTES;
