SELECT * FROM TABELA_DE_PRODUTOS;


--QUERO SABER QUANTAS EMBALAGENS DIFERENTES EU TENHO NOS MEUS PRODUTOS
SELECT EMBALAGEM FROM TABELA_DE_PRODUTOS;
SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS;
SELECT DISTINCT EMBALAGEM, SABOR FROM TABELA_DE_PRODUTOS WHERE SABOR = 'Maca';

-- QUERO SABER AS COMBINACOES DE SABORES E EMBALAGENS
SELECT DISTINCT EMBALAGEM, SABOR FROM TABELA_DE_PRODUTOS;

--Tendo em conta nossa tabela de produtos, execute uma consulta para obter o número de sabores existentes. Especifique o SQL que você executou para obter o resultado e a resposta propriamente dita.
SELECT * FROM TABELA_DE_PRODUTOS;
SELECT DISTINCT SABOR FROM TABELA_DE_PRODUTOS
SELECT COUNT(DISTINCT SABOR) FROM TABELA_DE_PRODUTOS;
