/*VAMOS FAZER UMA ANALISE PARA VER QUAIS SAO OS CLIENTES QUE ESTÃO LOCALIZADOS EM BAIRROS QUE EXISTEM VENDENDORES*/

SELECT COUNT(*) FROM TABELA_DE_CLIENTES;
-- 16 CLIENTES ---> 7 POSSUEM NOS SEUS BAIRROS, VENDEDORES.

SELECT COUNT(*) FROM TABELA_DE_VENDEDORES;
-- 4 VENDEDORES ---> 3 VENDEDORES POSSUEM NO SEUS BAIRROS CLIENTES.

/*TEMOS 16 CLIENTES MAS APÓS EFETUAR ESSA CONSULTA ELE LISTA APENAS 7, POIS APENAS 7 VENDEDORES RESIDEM PROXIMO AOS CLIENTES*/
SELECT 
 DISTINCT
 TV.NOME AS NOME_DO_VENDEDOR,
 TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
 TC.BAIRRO AS BAIRRO_DO_CLIENTE,
 TC.NOME AS NOME_DO_CLIENTE
FROM
 TABELA_DE_CLIENTES AS TC
INNER JOIN 
 TABELA_DE_VENDEDORES AS TV 
ON
 TC.BAIRRO = TV.BAIRRO


-- QUAL É O VENDEDOR QUE NÃO TEM CLIENTE NO SEU BAIRRO?
-- --SEGUNDA A CONSULTA A BAIXO A ROBERTA MARTINS EM COPACABANA
SELECT 
 DISTINCT
 TV.NOME AS NOME_DO_VENDEDOR,
 TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
 TC.BAIRRO AS BAIRRO_DO_CLIENTE,
 TC.NOME AS NOME_DO_CLIENTE
FROM
 TABELA_DE_CLIENTES AS TC
RIGHT JOIN
 TABELA_DE_VENDEDORES AS TV 
ON
 TC.BAIRRO = TV.BAIRRO
WHERE TC.NOME IS NULL;

-- QUAIS SÃO OS CLIENTES QUE TEM OU MORAM EM DETERMINADOS BAIRROS QUE NÃO POSSUEM VENDEDORES ?
--R; SEGUNDA AS CONSULTAS A BAIXO, SÃO 9 CLIENTES.
SELECT 
 DISTINCT
 TV.NOME AS NOME_DO_VENDEDOR,
 TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
 TC.BAIRRO AS BAIRRO_DO_CLIENTE,
 TC.NOME AS NOME_DO_CLIENTE
FROM
 TABELA_DE_CLIENTES AS TC
LEFT JOIN
 TABELA_DE_VENDEDORES AS TV 
ON
 TC.BAIRRO = TV.BAIRRO
WHERE TV.NOME IS NULL;









/*AS DUAS PERGUNTAS ACIMA PODERIAM SER RESPONDIDAS EM UMA UNICA CONSULTA COM O FULL JOIN*/
SELECT 
 DISTINCT
 TV.NOME AS NOME_DO_VENDEDOR,
 TV.BAIRRO AS BAIRRO_DO_VENDEDOR,
 TC.BAIRRO AS BAIRRO_DO_CLIENTE,
 TC.NOME AS NOME_DO_CLIENTE
FROM
 TABELA_DE_CLIENTES AS TC
FULL JOIN
 TABELA_DE_VENDEDORES AS TV 
ON
 TC.BAIRRO = TV.BAIRRO

