 use [SUCOS_FRUTAS]

SELECT EMBALAGEM, AVG(PRECO_DE_LISTA) AS PRECO_MEDIO
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM
HAVING AVG(PRECO_DE_LISTA) <= 10;



-- MESMA COISA QUE ACIMA
SELECT  MEDIA_EMBALAGENS.EMBALAGEM,
MEDIA_EMBALAGENS.PRECO_MEDIO FROM
(SELECT EMBALAGEM, AVG(PRECO_DE_LISTA) AS PRECO_MEDIO
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM) AS MEDIA_EMBALAGENS
WHERE MEDIA_EMBALAGENS.PRECO_MEDIO <= 10;

/*
Durante os exercícios anteriores, realizamos algumas consultas e entre elas estava a consulta abaixo que foi  resposta de um exercício anterior.
*/
SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;

/* Uma vez que essa consulta foi realizada nestes moldes, refaça esta consulta usando Subconsultas.*/
SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;

SELECT
	PRODUTOS_TOTAL.CODIGO_DO_PRODUTO,
	PRODUTOS_TOTAL.NOME_DO_PRODUTO,
	PRODUTOS_TOTAL.QUANTIDADE
FROM
	(SELECT 
		INF.CODIGO_DO_PRODUTO, 
		TP.NOME_DO_PRODUTO, 
		SUM(INF.QUANTIDADE) AS QUANTIDADE 
	FROM 
		ITENS_NOTAS_FISCAIS  INF
	INNER JOIN 
		TABELA_DE_PRODUTOS TP 
	ON 
		INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
	GROUP BY 
		INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO 
	) AS PRODUTOS_TOTAL 
WHERE 
	PRODUTOS_TOTAL.QUANTIDADE > 394000 
ORDER BY 
	PRODUTOS_TOTAL.QUANTIDADE DESC;
