SELECT * FROM TABELA_DE_CLIENTES


-- Aqui temos a soma dos limites de credito dos clientes por estado
SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS CREDITO 
FROM TABELA_DE_CLIENTES GROUP BY ESTADO;

-- Utilizando o having conseguimos fazer uma lista cuja a soma do limite de credito seja maior que 900 mil
SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS CREDITO 
FROM TABELA_DE_CLIENTES
GROUP BY ESTADO
HAVING SUM(LIMITE_DE_CREDITO) >= 900000;


/* Agora suponhamos que queremos ver o maior preço e o menor preço de todos os produtos por cada tipo
de embalagem */
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS PRECO_MAX, MIN(PRECO_DE_LISTA) AS PRECO_MIN 
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;

-- PODEMOS INCLUSIVE VER O MAIOR E O MENOR PREÇO DE PRODUTOS QUE SÃO MAIORES QUE 10 REAIS
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS PRECO_MAX, MIN(PRECO_DE_LISTA) AS PRECO_MIN 
FROM TABELA_DE_PRODUTOS 
WHERE PRECO_DE_LISTA >= 10 
GROUP BY EMBALAGEM;

--AGORA DA CONSULTA ACIMA QUEREMOS VER SOMENTES OS QUE POSSUEM O MAIOR PREÇO DE LISTA + QUE 20 REAIS
SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS PRECO_MAX, MIN(PRECO_DE_LISTA) AS PRECO_MIN 
FROM TABELA_DE_PRODUTOS 
WHERE PRECO_DE_LISTA >= 10 
GROUP BY EMBALAGEM
HAVING MAX(PRECO_DE_LISTA) >=20;


/*Vamos voltar aos itens das notas fiscais. Os dois exercícios anteriores olharam as vendas do produto '1101035' .Mas nossa empresa vendeu mais produtos. Verifique as quantidades totais de vendas de cada produto e
ordene do maior para o menor.*/

SELECT * FROM ITENS_NOTAS_FISCAIS 

SELECT CODIGO_DO_PRODUTO ,SUM(QUANTIDADE) AS QTD_VENDAS, SUM(PRECO) AS QTD_TOTAL 
FROM ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO
ORDER BY QTD_VENDAS DESC

SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS QUANTIDADE FROM ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO ORDER BY SUM(QUANTIDADE) DESC;

/*Vimos os produtos mais vendidos no exercício anterior. Agora, liste somente os produtos que venderam mais que 394000 unidades.*/


SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS QTD_TOTAL, SUM(PRECO) AS PRICE 
FROM ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO
HAVING SUM(QUANTIDADE) > 394000 
ORDER BY CODIGO_DO_PRODUTO DESC

SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS QUANTIDADE FROM ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO HAVING SUM(QUANTIDADE) > 394000 
ORDER BY SUM(QUANTIDADE) DESC;