SELECT * FROM TABELA_DE_PRODUTOS;
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA;
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA ASC;
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA DESC;


SELECT * FROM TABELA_DE_PRODUTOS ORDER BY NOME_DO_PRODUTO;
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM, NOME_DO_PRODUTO;
SELECT * FROM TABELA_DE_PRODUTOS ORDER BY EMBALAGEM DESC, NOME_DO_PRODUTO DESC;

SELECT TOP 5 * FROM TABELA_DE_PRODUTOS ORDER BY PRECO_DE_LISTA DESC;


/*Utilizando o banco de dados trabalhado em aula, execute duas querys SQL e identifique:
Qual foi a maior venda do produto "Linha Refrescante - 1 Litro - Morango/Limao" em quantidade? */
SELECT * FROM TABELA_DE_PRODUTOS 
WHERE nome_do_produto = 'Linha Refrescante - 1 Litro - Morango/Limao';
SELECT * FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO = '1101035' ORDER BY NOME_DO_PRODUTO;
SELECT * FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035' ORDER BY QUANTIDADE DESC;