USE SUCOS_FRUTAS
SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
-- 12 BAIRROS -> CLIENTES

SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES
-- 4 BAIRROS -> VENDEDORES

-- NÃO EXIBE OS DADOS REPETIDOS
SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION 
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;

-- MOSTRA TUDO
SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION  ALL
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;


-- DIZ A ORIGEM DA TABELA
SELECT DISTINCT BAIRRO, 'CLIENTE' AS ORIGEM FROM TABELA_DE_CLIENTES
UNION  ALL
SELECT DISTINCT BAIRRO, 'FORNECEDOR' AS ORIGEM  FROM TABELA_DE_VENDEDORES;
