Veja a consulta abaixo que foi resposta de um exercício anterior.

SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE FROM ITENS_NOTAS_FISCAIS  INF
INNER JOIN TABELA_DE_PRODUTOS TP 
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;Copiar código
Redesenhe esta consulta criando uma visão para a lista de quantidades totais por produto e aplicando a condição e ordenação sobre esta mesma visão.


CREATE VIEW  AS [dbo].[QUANTIDADE_PRODUTOS]
SELECT 
	INF.CODIGO_DO_PRODUTO, 
	TP.NOME_DO_PRODUTO, 
	SUM(INF.QUANTIDADE) AS QUANTIDADE
FROM 
	ITENS_NOTAS_FISCAIS  INF
INNER JOIN 
	TABELA_DE_PRODUTOS TP 
ON 
	INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY 
	INF.CODIGO_DO_PRODUTO,
	TP.NOME_DO_PRODUTO


SELECT
	* 
SELECT * FROM [dbo].[QUANTIDADE_PRODUTOS]
WHERE QUANTIDADE > 394000 
ORDER BY QUANTIDADE DESC;
