USE [SUCOS_FRUTAS]
GO

/****** Object:  View [dbo].[QUANTIDADE_PRODUTOS]    Script Date: 11/08/2024 12:51:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER VIEW [dbo].[QUANTIDADE_PRODUTOS] AS 
SELECT 
	INF.CODIGO_DO_PRODUTO, 
	TP.NOME_DO_PRODUTO, 
	SUM(INF.QUANTIDADE) AS QUANTIDADE
FROM 
	ITENS_NOTAS_FISCAIS  INF
INNER JOIN 
	TABELA_DE_PRODUTOS TP 
ON 
	INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY 
	INF.CODIGO_DO_PRODUTO,
	TP.NOME_DO_PRODUTO
GO


