CREATE VIEW MEDIA_EMBALAGENS AS 
SELECT EMBALAGEM, AVG(PRECO_DE_LISTA) AS PRECO_MEDIO
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM


SELECT * FROM MEDIA_EMBALAGENS;



SELECT EMBALAGEM, PRECO_MEDIO 
FROM MEDIA_EMBALAGENS
WHERE PRECO_MEDIO <= 10;




