SELECT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS] WHERE
[SABOR] = 'Laranja' /*Só ira trazer as diferenças no d sabor laranja*/

SELECT DISTINCT EMBALAGEM, TAMANHO, SABOR FROM [TABELA DE PRODUTOS]


SELECT DISTINCT EMBALAGEM, TAMANHO, SABOR FROM [TABELA DE PRODUTOS]



select * FROM dbo.[TABELA DE CLIENTES]

SELECT DISTINCT CIDADE, BAIRRO FROM [TABELA DE CLIENTES] WHERE
CIDADE = 'Rio de janeiro';