SELECT * FROM [TABELA DE PRODUTOS]

SELECT TOP 3 * FROM [TABELA DE PRODUTOS]

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'Laranja'

SELECT TOP 3 * FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'Laranja'

SELECT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT DISTINCT EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT DISTINCT TOP 3 EMBALAGEM, TAMANHO FROM [TABELA DE PRODUTOS]

SELECT * FROM [NOTAS FISCAIS]

select TOP 10 DATA, NUMERO from [NOTAS FISCAIS] WHERE DATA = '2017-01-01'

SELECT TOP 10 * FROM [NOTAS FISCAIS] 
WHERE [DATA] = '2017-01-01'