
SELECT SYSDATETIME()

SELECT SYSDATETIMEOFFSET() /*COLOCA A QUANTOS FUSOS HORARIO (-3) ESTOU AO FUSO HORARIO DE UTC(PADRÃO ZERO)*/

SELECT SYSUTCDATETIME()

SELECT CURRENT_TIMESTAMP

SELECT GETDATE()

SELECT GETUTCDATE()

SELECT DATENAME(YEAR,GETDATE())

SELECT DATENAME(MICROSECOND,GETDATE())

SELECT DATENAME(MINUTE,GETDATE())


SELECT DATENAME(MONTH,GETDATE())

SELECT DATEPART(MONTH,GETDATE())

SELECT DAY(GETDATE())

SELECT YEAR(GETDATE())

SELECT DATEFROMPARTS(2015,9,1)

SELECT DATENAME(MONTH,DATEFROMPARTS(2015,9,1))

SELECT DATETIME2FROMPARTS(2015,9,1,13,12,11,120,4)

SELECT DATEDIFF(YEAR, DATEFROMPARTS(2015,9,1), GETDATE()) /*DIFERENÇA ENTRE ANO*/

SELECT DATEDIFF(MONTH, DATEFROMPARTS(2015,9,1), GETDATE()) /*DIFERENÇA ENTRE MES*/

SELECT DATEADD(MONTH, 5, GETDATE())

SELECT ISDATE('2018-01-01')

SELECT ISDATE('2018-25-28')

SELECT * FROM [NOTAS FISCAIS]

SELECT [DATA], CONCAT(DATENAME(DAY, [DATA]), ' ', DATENAME(MONTH, [DATA]), ' ', DATENAME(YEAR, [DATA]))
FROM [NOTAS FISCAIS]


/*Crie uma consulta que mostre o nome e a idade dos clientes.*/

SELECT NOME, DATEDIFF(YEAR, ([DATA DE NASCIMENTO]), GETDATE()) AS 'IDADE' FROM [TABELA DE CLIENTES]

SELECT NOME, DATEDIFF(YEAR, [DATA DE NASCIMENTO], GETDATE()) AS IDADE
FROM [TABELA DE CLIENTES]








