select * from [TABELA DE CLIENTES]

select * from [ITENS NOTAS FISCAIS]

select * from [NOTAS FISCAIS]

select nf.CPF, SUBSTRING( CONVERT(varchar, nf.DATA, 120),1,7) as ANO_MES, inf.QUANTIDADE from [NOTAS FISCAIS] nf
inner join [ITENS NOTAS FISCAIS] inf
on nf.NUMERO = inf.NUMERO

select nf.CPF, SUBSTRING( CONVERT(varchar, nf.DATA, 120),1,7) as ANO_MES, SUM(inf.QUANTIDADE) AS QUANTIDADE_MES from [NOTAS FISCAIS] nf
inner join [ITENS NOTAS FISCAIS] inf
on nf.NUMERO = inf.NUMERO
GROUP BY nf.CPF, SUBSTRING( CONVERT(varchar, nf.DATA, 120),1,7)


SELECT TC.NOME, TC.[VOLUME DE COMPRA] FROM [TABELA DE CLIENTES] TC








			--JOIN COM A SUBQUERY
SELECT TC.NOME, CQ.ANO_MES, CQ.QUANTIDADE_MES, TC.[VOLUME DE COMPRA]
FROM
      -- INICIO DA SUBQUERY
          (select nf.CPF, SUBSTRING( CONVERT(varchar, nf.DATA, 120),1,7) as ANO_MES, SUM(inf.QUANTIDADE) AS QUANTIDADE_MES from [NOTAS FISCAIS] nf
          inner join [ITENS NOTAS FISCAIS] inf
          on nf.NUMERO = inf.NUMERO
          GROUP BY nf.CPF, SUBSTRING( CONVERT(varchar, nf.DATA, 120),1,7)) CQ
       -- FIM DA SUBQUERY
--JOIN COM A SUBQUERY
INNER JOIN [TABELA DE CLIENTES] TC ON TC.CPF = CQ.CPF





-- APLICANDO CONDICIONAL




SELECT AUX1.NOME, AUX1.ANO_MES, AUX1.QUANTIDADE_MES,

CASE WHEN AUX1.QUANTIDADE_MES <= AUX1.[VOLUME DE COMPRA] THEN 'VENDA VALIDA'
 WHEN AUX1.QUANTIDADE_MES > AUX1.[VOLUME DE COMPRA] THEN 'VENDA INVALIDA'
END AS STATUS_VENDA 

FROM
		
(SELECT TC.NOME, CQ.ANO_MES, CQ.QUANTIDADE_MES, TC.[VOLUME DE COMPRA]
FROM
(select nf.CPF, SUBSTRING( CONVERT(varchar, nf.DATA, 120),1,7) as ANO_MES, SUM(inf.QUANTIDADE) AS QUANTIDADE_MES from [NOTAS FISCAIS] nf
inner join [ITENS NOTAS FISCAIS] inf
on nf.NUMERO = inf.NUMERO
 GROUP BY nf.CPF, SUBSTRING( CONVERT(varchar, nf.DATA, 120),1,7)) CQ
INNER JOIN [TABELA DE CLIENTES] TC ON TC.CPF = CQ.CPF) AUX1
ORDER BY AUX1.NOME , AUX1.ANO_MES