SELECT * FROM [dbo].[TABELA DE PRODUTOS]

SELECT * FROM [TABELA DE PRODUTOS] ORDER BY [PREÇO DE LISTA]

SELECT * FROM [TABELA DE PRODUTOS] ORDER BY [PREÇO DE LISTA] DESC

SELECT * FROM [TABELA DE PRODUTOS] ORDER BY [NOME DO PRODUTO]

SELECT [EMBALAGEM], [NOME DO PRODUTO] FROM [TABELA DE PRODUTOS] 
ORDER BY [EMBALAGEM], [NOME DO PRODUTO]

SELECT [EMBALAGEM], [NOME DO PRODUTO] FROM [TABELA DE PRODUTOS] 
ORDER BY [EMBALAGEM] DESC, [NOME DO PRODUTO] ASC

select [NOME DO PRODUTO], [PREÇO DE LISTA]  from [TABELA DE PRODUTOS] WHERE [NOME DO PRODUTO] = 'Linha Refrescante - 1 Litro - Morango/Limão'
ORDER BY [PREÇO DE LISTA]

SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [NOME DO PRODUTO] = 'Linha Refrescante - 1 Litro - Morango/Limão'

SELECT * FROM [ITENS NOTAS FISCAIS]
WHERE [CODIGO DO PRODUTO] = '1101035'
ORDER BY QUANTIDADE DESC