-- Nessa consulta os dados vão vir repetidos.
SELECT 
TC.CPF AS CPF_DO_CADASTRO
, TC.NOME AS NOME_DO_CLIENTE
, NF.CPF AS CPF_DA_NOTA
FROM TABELA_DE_CLIENTES TC
INNER JOIN 
NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF

--Para resolver o problema em que os dados vem repetidos, nós utilizamos o distinct
SELECT DISTINCT
TC.CPF AS CPF_DO_CADASTRO
, TC.NOME AS NOME_DO_CLIENTE
, NF.CPF AS CPF_DA_NOTA
FROM TABELA_DE_CLIENTES TC
INNER JOIN 
NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF



--CONTANDO QUANTOS CLIENTES TEM NA TB CLIENTES
SELECT COUNT(*) FROM TABELA_DE_CLIENTES


INSERT INTO TABELA_DE_CLIENTES
(CPF, NOME, ENDERECO_1, ENDERECO_2, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO, IDADE,
GENERO, LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA)
VALUES('23412632331', 'Juliana Silva', 'R. Tramandai', '','Bangu','Rio de Janeiro','RJ','23400000',
'1998-08-05',33,'F',180000,24500,0);

SELECT COUNT(*) FROM TABELA_DE_CLIENTES

SELECT DISTINCT
TC.CPF AS CPF_DO_CADASTRO
, TC.NOME AS NOME_DO_CLIENTE
, NF.CPF AS CPF_DA_NOTA
FROM TABELA_DE_CLIENTES TC
INNER JOIN 
NOTAS_FISCAIS NF
ON TC.CPF = NF.CPF

--Suponhamos que tenhamos clientes novos como inseridos acima, e queiramos ver o cliente que não fez venda;
SELECT DISTINCT
TC.CPF AS CPF_DO_CADASTRO
, TC.NOME AS NOME_DO_CLIENTE
, NF.CPF AS CPF_DA_NOTA
FROM TABELA_DE_CLIENTES TC 
LEFT JOIN  --Mudamos para o left o que vai trazer todos os clientes, e só quem tem venda na tb notas fiscais
NOTAS_FISCAIS NF 
ON TC.CPF = NF.CPF


--Para ver o cliente que não fez venda
SELECT DISTINCT
TC.CPF AS CPF_DO_CADASTRO
, TC.NOME AS NOME_DO_CLIENTE
FROM TABELA_DE_CLIENTES TC 
LEFT JOIN  
NOTAS_FISCAIS NF 
ON TC.CPF = NF.CPF
WHERE NF.CPF IS NULL